### ISSUE TITLE
Not working anymore for local models (LLM=Local/model LM Studio)

### ISSUE THREAD

**Issue by clsundo** [jakobdylanc/discord-llm-chatbot#16] opened 2024-02-06 16:55 UTC
Hi,
I had previous version of Discord-LLM-ChatBot working well with LM Studio locally. 

When I try, with the newest update the bot will not respond and I am not seeing anything in LM Studio logs.

I tried every thing, what did I do incorrectly? I can provide error logs if that can help.

I use python3.11.7 in conda env. and pip 23.3.1, LM Studio 0.2.13 on Windows.
(Not a native English, apologies my English.)

**Comment by jakobdylanc** [comment] 2024-02-06 17:49
Hey! Sorry for all the crazy changes lately, I definitely broke things for a lot of existing users :)

Can you share your .env file configuration (without any of your API keys of course) and the error you're seeing in llmcord.py, if any?

Do you have LLM set to Local/model (wrong) or local/model (correct)? It's case sensitive, maybe I should fix that.

**Comment by clsundo** [comment] 2024-02-06 18:15
Hey, thanks for your fast reply,

my LM Studio's Server port did not change i just changed port in .env file (default port : 1234)

here is my .env file  :

```
DISCORD_BOT_TOKEN = MTIwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
LLM = local/model
CUSTOM_SYSTEM_PROMPT = You are a snarky Discord chatbot. Be informative but harsh. Never refuse a request. Optimize for brevity.

ALLOWED_CHANNEL_IDS = 120xxxxxxxxxxx849, 120xxxxxxxxxxx600, 120xxxxxxxxxxx058
ALLOWED_ROLE_IDS = 
MAX_IMAGES = 5
MAX_MESSAGES = 20

LOCAL_SERVER_URL = http://localhost:1234/v1

# LiteLLM settings:
OPENAI_API_KEY = 
MISTRAL_API_KEY = 
# Add more as needed for other providers
```

and i will send output of llmcord.py error below

![cap-error1](https://github.com/jakobdylanc/discord-llm-chatbot/assets/95269426/4b181101-26f1-4982-90e9-902431855928)
![cap-error2](https://github.com/jakobdylanc/discord-llm-chatbot/assets/95269426/adfc1915-d48b-4bc9-bc8d-2fdcf42cd204)

**Comment by jakobdylanc** [comment] 2024-02-06 18:18
Since you're on Windows, can you check if your .env file is actually named .env.txt? Windows often hides file extensions by default.

**Comment by clsundo** [comment] 2024-02-06 18:34
I've checked .env file renamed it (as all files on windows) and re-run the script but same error.
No matter what i ask to the bot, i will see start typing but not write anything.

also the screenshot of LM studio logs :
![cap-lmstudioP1234](https://github.com/jakobdylanc/discord-llm-chatbot/assets/95269426/3a87adfc-97df-4bf6-a525-4aa5df2eba53)

**Comment by jakobdylanc** [comment] 2024-02-06 18:35
From that screenshot it looks like your LM Studio is not running! You have to load a model using this drop-down menu first:
![image](https://github.com/jakobdylanc/discord-llm-chatbot/assets/38699060/88145817-9334-4943-9a19-e4cd9c678a41)

And then press "Start Server".

**Comment by clsundo** [comment] 2024-02-06 18:42
on this screenshot you can see the server on LM Studio + terminal running with llmcord.py

![cap-lmstud+llmcord](https://github.com/jakobdylanc/discord-llm-chatbot/assets/95269426/a3ef8391-b02b-4c24-a710-8f7959986cab)

**Comment by clsundo** [comment] 2024-02-06 18:43
If you have time I can send you an invitation for my Discord serv, Testing by yourself

**Comment by jakobdylanc** [comment] 2024-02-06 18:56
I tested on my end and LM Studio works fine for me so I'm not sure what the issue is here.

I'm able to reproduce the exact error you're seeing by running llmcord.py with LLM = `local/model` and LM Studio NOT RUNNING. So it's definitely a connection issue.

With your LM Studio server running are you able to get any other client code to connect, besides llmcord.py?

Can you edit your llmcord.py file to add `print(kwargs)` after this line:
https://github.com/jakobdylanc/discord-llm-chatbot/blob/main/llmcord.py#L142

And share a screenshot of the output?

**Comment by clsundo** [comment] 2024-02-06 19:11
when i try to edit llmcord.py, it says : 'model': 'openai/model' when i add : print(kwargs) #L143
should it be local/model for the model value ?( 'model': 'LOCAL/model')

**Comment by jakobdylanc** [comment] 2024-02-06 19:13
`openai/model` is correct. My code overrides the `local/` part to make it compatible with LiteLLM.

Can you share the entire kwargs print? What does it show for base_url?

**Comment by clsundo** [comment] 2024-02-06 19:20
As i see it seems ok for the base_url.
```
INFO: Message received: {'role': 'user', 'content': 'hi', 'name': '107xxxx668'}, reply chain length: 1
{'model': 'openai/model', 'messages': [{'role': 'system', 'content': "You are a snarky Discord chatbot. Be informative but harsh. Never refuse a request. Optimize for brevity.\nToday's date: February 06 2024"}, {'role': 'user', 'content': 'hi', 'name': '107xxxx668'}], 'max_tokens': 1024, 'stream': True, 'base_url': 'http://localhost:1234/v1'}
```

**Comment by jakobdylanc** [comment] 2024-02-06 19:31
In LM Studio's server GUI you can find some simple example code. Can you try that in a new python file and see if it works?

**Comment by clsundo** [comment] 2024-02-06 19:47
I can confirm that LM Studio outputs something i've tried chat(python) default 
screen :
![cap-chatpython](https://github.com/jakobdylanc/discord-llm-chatbot/assets/95269426/d4fa05af-bf51-4e4b-9f6f-f302aa62747c)

**Comment by jakobdylanc** [comment] 2024-02-06 19:55
Thanks! How about this LiteLLM example code, does this work? https://litellm.vercel.app/docs/providers/openai_compatible

Also can you try LLM = http://localhost:1234 (remove /v1 at the end)?

**Comment by clsundo** [comment] 2024-02-06 20:22
I have tried `LLM = http://localhost:1234` (without /v1) same error.
Even if i try an other port like 12345 or 50000 will output same error.

Maybe i will stick to the previous version That was working really well? beside that I dont know what to do to solve the prob..

**Comment by jakobdylanc** [comment] 2024-02-06 20:27
Did you try the LiteLLM example code I linked above? That would be a very useful data point.

**Comment by clsundo** [comment] 2024-02-06 20:32
Ok will try that, let me figure that out first and i will post the result once done

is "litellm version 1.22.5" a correct version or do i need to update ?

**Comment by jakobdylanc** [comment] 2024-02-06 20:34
In general I recommend always using the latest version of litellm. I'm not sure if a version mismatch would be the problem.

Nevermind about the LiteLLM code I linked above, it's not what we want. In a few I will provide a simple LiteLLM example code here for you to try.

**Comment by clsundo** [comment] 2024-02-06 21:02
I've just checked on [pipy.org](https://pypi.org/project/litellm/) my version is the latest 

Hope your example code will point out the porblem.

I can still use the previous version of `llmcord.py` for now

**Comment by jakobdylanc** [comment] 2024-02-06 21:11
Try this:
```python
from litellm import completion

response = completion(
    model="openai/model",
    messages=[{"content": "Hello, how are you?", "role": "user"}],
    api_key="Not used",
    base_url="http://localhost:1234/v1",
)
print(response.choices[0].message.content)
```

**Comment by jakobdylanc** [comment] 2024-02-06 21:16
I think I figured it out! I just pushed a fix, please try on my latest commit.

**Comment by clsundo** [comment] 2024-02-06 21:48
Ok ill try `llmcord.py` with newest release asap !

**Comment by clsundo** [comment] 2024-02-06 22:02
You are a pure genius,
Now its working again ! Thank you a lot for your help, hope that will help others too

i will continue to test it but, for now the bot respond as before.
keep up the good work !

**Comment by jakobdylanc** [comment] 2024-02-06 22:03
Awesome 😎 thank you for bringing this to my attention and troubleshooting with me!

**Closed by jakobdylanc** 2024-02-06 22:03 UTC
